In [3]:
import numpy as np
import pandas as pd

In [4]:
def gen_dumb_price():
    
    # start with four random columns
    v = np.random.normal(size=(1000,4))
    df = pd.DataFrame(v, columns='low open close high'.split())

    # smooth out
    df = df.rolling(10).mean()

    # add a bit of push
    ma = df['low'].rolling(20).mean().diff()
    for col in df.columns:
        df[col] *= ma*100

    # arrange so low is lowest each period, high highest, open and close in between
    df.values.sort(axis=1)

    # add price variation over time and some amplitude
    df = (df.T + np.sin(df.index/87) * 3 + np.cos(df.index/201) * 5).T + 20

    # some green, some red candles
    flip = df['open'].shift(-1) <= df['open']
    df.loc[flip,'open'],df.loc[flip,'close'] = df['close'].copy(),df['open'].copy()

    # price action => volume
    df['volume'] = df['high'] - df['low']

    # epoch time
    df.index = np.linspace(1608332400-60*1000, 1608332400, 1000)

    return df['open close high low volume'.split()].dropna()

In [5]:
data = gen_dumb_price()
data

                   open      close       high        low    volume
1.608274e+09  25.926752  25.342855  26.135051  24.883927  1.251123
1.608274e+09  25.236402  26.332982  26.366535  25.167977  1.198558
1.608274e+09  25.637582  25.970473  26.175094  25.530614  0.644480
1.608274e+09  25.774221  26.103657  26.439989  25.241703  1.198286
1.608274e+09  26.008007  25.942789  26.491928  25.492050  0.999878
...                 ...        ...        ...        ...       ...
1.608332e+09  18.110316  19.268468  20.812573  16.118196  4.694377
1.608332e+09  19.210487  18.643081  19.316231  17.144458  2.171773
1.608332e+09  18.307677  18.458764  18.607909  18.031208  0.576701
1.608332e+09  18.578621  18.578659  18.580969  18.567370  0.013600
1.608332e+09  18.602475  18.607447  18.627820  18.504559  0.123261

[971 rows x 5 columns]